name:                putio-haskell
version:             0.1.0.0
github:              "bbyalcinkaya/putio-haskell"
license:             BSD3
author:              "Burak Bilge Yalçınkaya"
maintainer:          "example@example.com"
copyright:           "2022 Burak Bilge Yalçınkaya"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bbyalcinkaya/putio-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-client
- http-client
- text
- aeson
- http-client-tls
- time
- mtl

library:
  source-dirs: src

executables:
  putio-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - putio-haskell

tests:
  putio-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - putio-haskell
